export const personalInfo = {
  name: "Agam Jindal",
  title: "Full Stack Developer",
  tagline: "Leveling Up One Commit at a Time",
  email: "agamjindal372005@gmail.com",
  phone: "+91-8168718747",
  linkedin: "https://www.linkedin.com/in/agam-jindal-379352298/",
  github: "https://github.com/Agam3705",
  location: "Phagwara, Punjab",
  college: "Lovely Professional University",
  cgpa: "7.63",
  bio: "I'm a Computer Science student and full-stack developer who loves building things that matter. From disaster response platforms to real-time collaborative whiteboards — I turn complex ideas into polished, production-ready apps.",
  level: 14,
  xp: 8500,
  maxXp: 10000,
  playerClass: "Full Stack Mage",
};

export const skills = [
  { name: "JavaScript", level: 88, category: "Languages", icon: "SiJavascript", color: "#F7DF1E" },
  { name: "Java", level: 82, category: "Languages", icon: "SiJava", color: "#ED8B00" },
  { name: "Python", level: 75, category: "Languages", icon: "SiPython", color: "#3776AB" },
  { name: "C/C++", level: 78, category: "Languages", icon: "SiCplusplus", color: "#00599C" },
  { name: "PHP", level: 70, category: "Languages", icon: "SiPhp", color: "#777BB3" },
  { name: "SQL", level: 80, category: "Languages", icon: "SiMysql", color: "#4479A1" },
  { name: "React.js", level: 85, category: "Frameworks", icon: "SiReact", color: "#61DAFB" },
  { name: "Node.js", level: 84, category: "Frameworks", icon: "SiNodedotjs", color: "#339933" },
  { name: "Express.js", level: 82, category: "Frameworks", icon: "SiExpress", color: "#ffffff" },
  { name: "Tailwind CSS", level: 88, category: "Frameworks", icon: "SiTailwindcss", color: "#38BDF8" },
  { name: "Socket.io", level: 80, category: "Frameworks", icon: "SiSocketdotio", color: "#010101" },
  { name: "MongoDB", level: 82, category: "Tools", icon: "SiMongodb", color: "#47A248" },
  { name: "MySQL", level: 78, category: "Tools", icon: "SiMysql", color: "#4479A1" },
  { name: "Git/GitHub", level: 85, category: "Tools", icon: "SiGithub", color: "#A78BFA" },
  { name: "Vercel/Render", level: 78, category: "Tools", icon: "SiVercel", color: "#ffffff" },
];

export const projects = [
  {
    id: 1,
    title: "Resq-Connect",
    subtitle: "Disaster Response Platform",
    description: "A full-stack disaster response platform featuring a Tactical Command Center with a live map interface powered by Leaflet.js for real-time unit tracking. Includes One-Touch SOS, secure Document Locker with multi-role auth, and a 'Lite Mode' for low-connectivity areas.",
    techStack: ["MERN", "Socket.io", "Leaflet.js", "Tailwind CSS", "Vite"],
    github: "https://github.com/Agam3705/ResQ-Connect.git",
    live: "https://resq-connect0.vercel.app",
    period: "Dec '25",
    difficulty: "Hard",
    xpReward: 650,
    icon: "🚨",
    color: "#FF6B6B",
    type: "Web",
  },
  {
    id: 2,
    title: "BoardRoom",
    subtitle: "Real-Time Collaborative Whiteboard",
    description: "A high-performance whiteboard platform with infinite canvas, advanced object manipulation, Magnetic Connectors, and a glassmorphic UI. Features live cursor tracking via Socket.io, WebRTC video bubbles, role-based access control, 'Time Machine' history replay, private Markdown notes, and real-time chat.",
    techStack: ["MERN", "Socket.io", "WebRTC", "Konva.js", "Tailwind CSS", "Zustand", "Vite"],
    github: "https://github.com/Agam3705/BoardRoom.git",
    live: "https://boardroom0.vercel.app",
    period: "Aug '25",
    difficulty: "Hard",
    xpReward: 750,
    icon: "🖌️",
    color: "#4ECDC4",
    type: "Web",
  },
  {
  id: 3,
  title: "Aura Confess",
  subtitle: "Anonymous Social Networking & Messaging",
  description: "A secure, privacy-focused confession platform featuring end-to-end encrypted anonymous messaging, proximity-based discovery, and an AI-moderated 'Aura' feed. Includes real-time notifications, customizable user avatars, and a seamless interface for sharing secrets or feedback without revealing identity.",
  techStack: ["MERN", "Socket.io", "Firebase", "Tailwind CSS", "Redux Toolkit", "Cloudinary"],
  github: "https://github.com/Agam3705/AuraConfess.git",
  live: "https://aura-confess0.vercel.app",
  period: "Jan '26",
  difficulty: "Medium",
  xpReward: 600,
  icon: "👻",
  color: "#A855F7",
  type: "Web",
  },
];

export const achievements = [
  {
    id: 1,
    title: "Club President",
    description: "Directed technical workshops as President of the Microsoft Achievers Club to enhance student professional skills.",
    icon: "👑",
    date: "mar'24 – jan'26",
    type: "leadership",
    rarity: "Legendary",
    color: "#FFD700",
  },
  {
    id: 2,
    title: "Android Dev Trained",
    description: "Completed intensive Android App Development training at LPU — built 5 mini-projects using Java Swing & AWT.",
    icon: "📱",
    date: "Jul'25",
    type: "training",
    rarity: "Rare",
    color: "#4ADE80",
  },
  {
    id: 3,
    title: "Cloud Computing",
    description: "Cloud Computing Certification — NPTEL",
    icon: "☁️",
    date: "Apr'25",
    type: "certification",
    rarity: "Rare",
    color: "#FB923C",
  },
  {
    id: 4,
    title: "Computational Theory",
    description: "Computational Theory: Language Principles & Finite Automata — Infosys",
    icon: "🧠",
    date: "Aug'25",
    type: "certification",
    rarity: "Rare",
    color: "#38BDF8",
  },
  {
    id: 5,
    title: "Generative AI No-Code",
    description: "Build Generative AI Apps and Solutions with No-Code Tools — Infosys",
    icon: "🤖",
    date: "Aug'25",
    type: "certification",
    rarity: "Rare",
    color: "#38BDF8",
  },
  {
    id: 6,
    title: "Prompt Engineering",
    description: "ChatGPT-4 Prompt Engineering: ChatGPT, Generative AI & LLM — Infosys",
    icon: "💬",
    date: "Aug'25",
    type: "certification",
    rarity: "Rare",
    color: "#38BDF8",
  },
  {
    id: 7,
    title: "Mastering GenAI",
    description: "Master Generative AI & Generative AI tools (ChatGPT & more) — Infosys",
    icon: "🌟",
    date: "Aug'25",
    type: "certification",
    rarity: "Rare",
    color: "#38BDF8",
  },
  {
    id: 8,
    title: "CTF Runner-up",
    description: "Secured a runner-up position at the Encrypt Edge CTF by utilizing AI models to resolve security vulnerabilities.",
    icon: "🛡️",
    date: "2025",
    type: "competition",
    rarity: "Epic",
    color: "#C084FC",
  },
  {
    id: 9,
    title: "Web Dev Bootcamp",
    description: "Complete Web Development Bootcamp — Udemy",
    icon: "🌐",
    date: "Feb'25",
    type: "certification",
    rarity: "Uncommon",
    color: "#F472B6",
  },
];

export const timeline = [
  {
    year: "Aug'23 – Present",
    title: "B.Tech – Computer Science",
    subtitle: "Lovely Professional University, Phagwara, Punjab",
    description: "CGPA: 7.63 | Full Stack Dev journey with MERN, Java, Python, DSA, and more.",
    type: "education",
    icon: "🎓",
  },
  {
    year: "Mar'21 – May'23",
    title: "Intermediate (12th) — PCM",
    subtitle: "B.B.V.P. Sr. Sec. School, Sonipat, Haryana",
    description: "Percentage: 77.6%",
    type: "education",
    icon: "📘",
  },
  {
    year: "Apr'20 – May'21",
    title: "Matriculation (10th)",
    subtitle: "B.B.V.P. Sr. Sec. School, Sonipat, Haryana",
    description: "Percentage: 93.4%",
    type: "education",
    icon: "📗",
  },
];
