export const personalInfo = {
  name: "Kumari Kriti Singh",
  title: "Full Stack Developer",
  tagline: "Leveling Up One Commit at a Time",
  email: "kumakritisingh5@gmail.com",
  phone: "+91-7488223232",
  linkedin: "https://linkedin.com/in/kritisingh7488",
  github: "https://github.com/kritisingh7488",
  location: "Phagwara, Punjab",
  college: "Lovely Professional University",
  cgpa: "7.68",
  bio: "I'm a Computer Science student and full-stack developer who loves building things that matter. From Java Swing desktop apps to Node.js web platforms — I turn ideas into reality.",
  level: 12,
  xp: 7480,
  maxXp: 10000,
  playerClass: "Full Stack Mage",
};

export const skills = [
  { name: "JavaScript", level: 85, category: "Languages", icon: "SiJavascript", color: "#F7DF1E" },
  { name: "Java", level: 80, category: "Languages", icon: "SiJava", color: "#ED8B00" },
  { name: "C/C++", level: 75, category: "Languages", icon: "SiCplusplus", color: "#00599C" },
  { name: "PHP", level: 70, category: "Languages", icon: "SiPhp", color: "#777BB3" },
  { name: "ReactJS", level: 82, category: "Frameworks", icon: "SiReact", color: "#61DAFB" },
  { name: "Node.js", level: 78, category: "Frameworks", icon: "SiNodedotjs", color: "#339933" },
  { name: "Tailwind CSS", level: 85, category: "Frameworks", icon: "SiTailwindcss", color: "#38BDF8" },
  { name: "HTML/CSS", level: 90, category: "Frameworks", icon: "SiHtml5", color: "#E34F26" },
  { name: "MySQL", level: 75, category: "Tools", icon: "SiMysql", color: "#4479A1" },
  { name: "Git/GitHub", level: 80, category: "Tools", icon: "SiGithub", color: "#A78BFA" },
  { name: "DSA", level: 78, category: "Core CS", icon: "SiLeetcode", color: "#FFA116" },
  { name: "OOP", level: 82, category: "Core CS", icon: "SiCodeforces", color: "#7C3AED" },
];

export const projects = [
  {
    id: 1,
    title: "Paint Application",
    subtitle: "Desktop Creative Tool",
    description: "A desktop-based paint tool using Java and Swing with smooth responsive drawing capabilities. Includes pencil, shapes, color picker, fill, and eraser with adjustable brush controls.",
    techStack: ["Java", "Swing", "GUI Development", "Desktop App"],
    github: "https://github.com/kritisingh7488",
    period: "Jun'25 – Jul'25",
    difficulty: "Medium",
    xpReward: 350,
    icon: "🎨",
    color: "#FF6B6B",
    type: "Desktop",
  },
  {
    id: 2,
    title: "Knowledge Management Portal",
    subtitle: "Full Stack Web Platform",
    description: "A structured knowledge portal with clean HTML/Tailwind UI. PHP + Node.js backend to handle requests, MySQL for data storage, jQuery for dynamic interactions and content navigation.",
    techStack: ["HTML", "Tailwind CSS", "PHP", "Node.js", "MySQL", "jQuery"],
    github: "https://github.com/kritisingh7488",
    period: "Jan'25 – Apr'25",
    difficulty: "Hard",
    xpReward: 500,
    icon: "📚",
    color: "#4ECDC4",
    type: "Web",
  },
  {
    id: 3,
    title: "Energy Efficient CPU Scheduler",
    subtitle: "Algorithm Simulator",
    description: "A web tool to simulate CPU scheduling algorithms with an energy-efficient approach. Users can test multiple algorithms, observe real-time performance with Gantt chart visualizations.",
    techStack: ["HTML", "Tailwind CSS", "JavaScript", "PHP", "Web Simulation"],
    github: "https://github.com/kritisingh7488",
    period: "Jan'25 – Mar'25",
    difficulty: "Hard",
    xpReward: 450,
    icon: "⚡",
    color: "#A78BFA",
    type: "Web",
  },
];

export const achievements = [
  {
    id: 1,
    title: "5-Star Coder",
    description: "Earned a 5-star C++ rating on HackerRank",
    icon: "⭐",
    date: "Oct'25",
    type: "competitive",
    rarity: "Legendary",
    color: "#FFD700",
  },
  {
    id: 2,
    title: "Achievers Hunt Champion",
    description: "Secured 2nd position among 100+ participants at LPU",
    icon: "🏆",
    date: "May'24",
    type: "competition",
    rarity: "Epic",
    color: "#C084FC",
  },
  {
    id: 3,
    title: "Cloud Computing Cert",
    description: "NPTEL Cloud Computing Certification",
    icon: "☁️",
    date: "Apr'25",
    type: "certification",
    rarity: "Rare",
    color: "#38BDF8",
  },
  {
    id: 4,
    title: "Computer Networking",
    description: "Coursera Computer Communications Certification",
    icon: "🌐",
    date: "Nov'24",
    type: "certification",
    rarity: "Rare",
    color: "#4ADE80",
  },
  {
    id: 5,
    title: "Social Entrepreneur",
    description: "Social Entrepreneurship — Sanjivani Shakti Sewa Samiti",
    icon: "🌱",
    date: "Jul'24",
    type: "certification",
    rarity: "Uncommon",
    color: "#FB923C",
  },
  {
    id: 6,
    title: "Data Structures Training",
    description: "Fundamentals of Data Structures - LPU Training",
    icon: "🏗️",
    date: "Jul'25",
    type: "certification",
    rarity: "Epic",
    color: "#60A5FA",
  },
];

export const timeline = [
  {
    year: "Aug'23 – Present",
    title: "B.Tech – Computer Science",
    subtitle: "Lovely Professional University, Phagwara, Punjab",
    description: "CGPA: 7.68 | Full Stack Dev journey with MERN, Java, DSA, and more.",
    type: "education",
    icon: "🎓",
  },

  {
    year: "Apr'21 – Jun'22",
    title: "Intermediate (12th)",
    subtitle: "Saraswati Shishu Vidya Mandir, Dhurwa, Ranchi",
    description: "Percentage: 89%",
    type: "education",
    icon: "📘",
  },
  {
    year: "Apr'19 – Jun'20",
    title: "Matriculation (10th)",
    subtitle: "Saraswati Shishu Vidya Mandir, Dhurwa, Ranchi",
    description: "Percentage: 85%",
    type: "education",
    icon: "📗",
  },
];
